version: "3.8"

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3307:3306"

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 restapi.wsgi:application --workers=3
    volumes:
      - .:/restapi
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - /restapi/.env

volumes:
  db_data:
